language: python
# ===== Linux ======
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
  - "3.6-dev"
  - "3.7-dev"
  - "3.8-dev"
matrix:
  fast_finish: true  # allows to determine results when linux builds finish, without waiting for osx and windows builds
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "3.8-dev"
    # - os: windows
    # - os: osx
  include:
    # ======= OSX ========
    - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
      script: python3 -m pytest
      after_success: python 3 -m codecov
    - name: "Python 3.7.3 on macOS 10.14"
      os: osx
      osx_image: xcode10.2  # Python 3.7.3 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
      script: python3 -m pytest
      after_success: python 3 -m codecov
    #  ====== WINDOWS =========
    - name: "Python 3.5.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.5.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    - name: "Python 3.6.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
# notifications:
#   email:
#     on_success: change
#     on_failure: always
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install ".[test]"
script: pytest
after_success:
  - codecov
